; 系统变量配置
[system]
name=Hoshizora
key=Hoshizora
version=StarNight Engine 3 Years

; 覆盖默认设置
[config]
fullscreen=false
interruptclip=true
fastforwardunread=false
stopfastonselection=true
golbalvolume=1
bgmvolume=0.5
sevolume=0.7
clipvolume=0.7
uisevolume=1
textspeed=0.5
autoreadspeed=0.5
textboxopacity=0.3
language=zh-CN

; 用户配置
[user]