; 系统变量配置
[info]
name=demo
version=StarNight Engine 3 Years

[graphic]
width=1280
height=720
mode=auto

; 覆盖默认设置
[config]
FullScreen=false
InterruptClip=true
FastForwardUnread=false
StopFastOnSelection=true
GolbalVolume=1
BGMVolume=0.5
SEVolume=0.7
ClipVolume=0.7
UISEVolume=1
TextSpeed=0.5
AutoReadSpeed=0.5
TextBoxOpacity=0.3
Language=zh-CN

; 用户配置
[user]